version: "3.8"
services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    # bindするアドレスとポート指定しないといけない
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3011:3000"
    tty: true
    volumes:
      - ./hello_app:/app/hello_app
